// components/navigation.tsx
"use client"

import { useState } from "react"
import Link from "next/link"
import { usePathname } from "next/navigation"
import { Button } from "@/components/ui/button"
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet"
import { Menu, Code, User, Briefcase, Mail, Home } from "lucide-react"

export default function Navigation() {
  const [isOpen, setIsOpen] = useState(false)
  const pathname = usePathname()

  const navItems = [
    { href: "/", label: "Início", icon: <Home className="w-4 h-4" /> },
    { href: "/sobre", label: "Sobre", icon: <User className="w-4 h-4" /> },
    { href: "/habilidades", label: "Habilidades", icon: <Code className="w-4 h-4" /> },
    { href: "/projetos", label: "Projetos", icon: <Briefcase className="w-4 h-4" /> },
    { href: "/contato", label: "Contato", icon: <Mail className="w-4 h-4" /> },
  ]

  const isActive = (href: string) => {
    if (href === "/") {
      return pathname === "/"
    }
    return pathname.startsWith(href)
  }

  return (
    <nav className="sticky top-0 z-50 w-full border-b bg-white/95 dark:bg-slate-900/95 backdrop-blur supports-[backdrop-filter]:bg-white/60">
      <div className="container mx-auto px-4">
        <div className="flex h-16 items-center justify-between">
          {/* Logo */}
          <Link href="/" className="flex items-center space-x-2">
            <div className="w-8 h-8 bg-gradient-to-r from-blue-600 to-purple-600 rounded-lg flex items-center justify-center">
              <span className="text-white font-bold text-sm">JS</span>
            </div>
            <span className="font-bold text-xl text-slate-900 dark:text-white">Diogo Bassalobre</span>
          </Link>

          {/* Desktop Navigation */}
          <div className="hidden md:flex items-center space-x-1">
            {navItems.map((item) => (
              <Button
                key={item.href}
                asChild
                variant={isActive(item.href) ? "default" : "ghost"}
                className={isActive(item.href) ? "bg-blue-600 hover:bg-blue-700" : ""}
              >
                <Link href={item.href} className="flex items-center space-x-2">
                  {item.icon}
                  <span>{item.label}</span>
                </Link>
              </Button>
            ))}
          </div>

          {/* Mobile Navigation */}
          <div className="md:hidden">
            <Sheet open={isOpen} onOpenChange={setIsOpen}>
              <SheetTrigger asChild>
                <Button variant="ghost" size="icon">
                  <Menu className="h-6 w-6" />
                </Button>
              </SheetTrigger>
              <SheetContent side="right" className="w-80">
                <div className="flex items-center justify-between mb-8">
                  <div className="flex items-center space-x-2">
                    <div className="w-8 h-8 bg-gradient-to-r from-blue-600 to-purple-600 rounded-lg flex items-center justify-center">
                      <span className="text-white font-bold text-sm">JS</span>
                    </div>
                    <span className="font-bold text-xl">Diogo Bassalobre</span>
                  </div>
                </div>
                <div className="space-y-4">
                  {navItems.map((item) => (
                    <Button
                      key={item.href}
                      asChild
                      variant={isActive(item.href) ? "default" : "ghost"}
                      className={`w-full justify-start ${isActive(item.href) ? "bg-blue-600 hover:bg-blue-700" : ""}`}
                      onClick={() => setIsOpen(false)}
                    >
                      <Link href={item.href} className="flex items-center space-x-3">
                        {item.icon}
                        <span>{item.label}</span>
                      </Link>
                    </Button>
                  ))}
                </div>
              </SheetContent>
            </Sheet>
          </div>
        </div>
      </div>
    </nav>
  )
}

// src/app/components/navigation/navigation.component.ts
import { Component, inject } from "@angular/core"
import { CommonModule } from "@angular/common"
import { Router, RouterModule } from "@angular/router"
import { LucideAngularModule, Home, User, Code, Briefcase, Mail, Menu, X } from "lucide-angular"

@Component({
  selector: "app-navigation",
  standalone: true,
  imports: [CommonModule, RouterModule, LucideAngularModule],
  template: `
    <nav class="sticky top-0 z-50 w-full border-b bg-white/95 dark:bg-slate-900/95 backdrop-blur supports-[backdrop-filter]:bg-white/60">
      <div class="container mx-auto px-4">
        <div class="flex h-16 items-center justify-between">
          <!-- Logo -->
          <a routerLink="/" class="flex items-center space-x-2">
            <div class="w-8 h-8 bg-gradient-to-r from-blue-600 to-purple-600 rounded-lg flex items-center justify-center">
              <span class="text-white font-bold text-sm">DB</span>
            </div>
            <span class="font-bold text-xl text-slate-900 dark:text-white">Diogo Bassalobre</span>
          </a>

          <!-- Desktop Navigation -->
          <div class="hidden md:flex items-center space-x-1">
            <a
              *ngFor="let item of navItems"
              [routerLink]="item.href"
              routerLinkActive="bg-blue-600 text-white hover:bg-blue-700"
              [routerLinkActiveOptions]="{ exact: item.href === '/' }"
              class="flex items-center space-x-2 px-4 py-2 rounded-md text-sm font-medium transition-colors hover:bg-slate-100 dark:hover:bg-slate-800"
            >
              <lucide-angular [img]="item.icon" class="w-4 h-4"></lucide-angular>
              <span>{{ item.label }}</span>
            </a>
          </div>

          <!-- Mobile Menu Button -->
          <button
            (click)="toggleMobileMenu()"
            class="md:hidden p-2 rounded-md hover:bg-slate-100 dark:hover:bg-slate-800"
          >
            <lucide-angular [img]="isMenuOpen ? XIcon : MenuIcon" class="w-6 h-6"></lucide-angular>
          </button>
        </div>

        <!-- Mobile Navigation -->
        <div
          *ngIf="isMenuOpen"
          class="md:hidden border-t bg-white dark:bg-slate-900 absolute left-0 right-0 top-16 shadow-lg"
        >
          <div class="container mx-auto px-4 py-4 space-y-2">
            <a
              *ngFor="let item of navItems"
              [routerLink]="item.href"
              routerLinkActive="bg-blue-600 text-white"
              [routerLinkActiveOptions]="{ exact: item.href === '/' }"
              (click)="closeMobileMenu()"
              class="flex items-center space-x-3 px-4 py-3 rounded-md text-sm font-medium transition-colors hover:bg-slate-100 dark:hover:bg-slate-800 w-full"
            >
              <lucide-angular [img]="item.icon" class="w-4 h-4"></lucide-angular>
              <span>{{ item.label }}</span>
            </a>
          </div>
        </div>
      </div>
    </nav>
  `,
})
export class NavigationComponent {
  private router = inject(Router)

  isMenuOpen = false

  // Icons
  HomeIcon = Home
  UserIcon = User
  CodeIcon = Code
  BriefcaseIcon = Briefcase
  MailIcon = Mail
  MenuIcon = Menu
  XIcon = X

  navItems = [
    { href: "/", label: "Início", icon: Home },
    { href: "/sobre", label: "Sobre", icon: User },
    { href: "/habilidades", label: "Habilidades", icon: Code },
    { href: "/projetos", label: "Projetos", icon: Briefcase },
    { href: "/contato", label: "Contato", icon: Mail },
  ]

  toggleMobileMenu() {
    this.isMenuOpen = !this.isMenuOpen
  }

  closeMobileMenu() {
    this.isMenuOpen = false
  }
}
